### ISSUE TITLE
Test budget as time hinders reproducibility of results

### ISSUE THREAD

**Issue by iporres** [se2p/tool-competition-av#92]
Currently, the competition uses time as the overall test budget. This has some benefits but also an important drawback: it makes the competition results more difficult if not impossible to reproduce. We have had problems reproducing the results from the  2021 competition and we suspect this may be due to differences in computer speeds. 

It is usually recommended that algorithm benchmarks are independent of the underlaying computer and are based in a number of iterations and not in time, when possible.

I suggest that the overall test budget is based on a number of  simulated tests (maximum number of valid roads that are used as scenarios by the simulator). 

This is to define the stoping condition for the testing process and it  does not exclude collecting other metrics such as:

-  the number of invalid roads 
-  time used to generate all the roads
-  time used to simulate the valid roads

**Comment by p1ndsvin** [comment]
Dear @iporres, thanks for your suggestion. 

We agree that using real time for the benchmarking may threaten our results’ validity. Last year, we mitigated this threat and ensured a fair comparison by using the same dedicated machine meeting the minimum BeamNG requirements to run all the experiments. We shared the details of our hardware and software setup in Section III.D of the tool competition report. Moreover, we ran each test generator multiple times to address their intrinsic randomness. Of course, these results may not generalise to other machines.

We decided to use real time since it takes into account crucial aspects of search based test generation such as time to generate/mutate/select a test and time to execute a test. Notably, this metric highlights the resources “wasted” for generating invalid tests. We deem these aspects as crucial to compare generators for practical usage (e.g., how long should a tester need to wait to see the results?).

We discussed the test budget you suggested (number of generated valid roads) and it suffers from a major drawback: it does not consider the difference between different road lengths and would be biased in favour of test generators that generate longer roads (which in turn consume more real time and have higher chances to expose a problem). The additional metrics you suggested (time used to generate all the roads and time used to simulate the valid roads) still rely on real time.

An alternative to real time is the simulation time (i.e., time measured by BeamNG during the simulation) which is independent of the host machine and of real time. This alternative alone would consider only the time spent for simulations, not taking into account the efficiency of test generators in generating/mutating/selecting tests. 

For these reasons, we decided to design a new test budget that takes into account both real time and simulation time.
